name: Build Release APK

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble Release
        run: ./gradlew assembleRelease

      - name: Sign Release APK
        uses: Dinesh2811/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.MYAPP_RELEASE_STORE_FILE }}
          keyStorePassword: ${{ secrets.MYAPP_RELEASE_STORE_PASSWORD }}
          alias: ${{ secrets.MYAPP_RELEASE_KEY_ALIAS }}
          keyPassword: ${{ secrets.MYAPP_RELEASE_KEY_PASSWORD }}

      - name: Copy release APK to root
        run: cp app/build/outputs/apk/release/app-release.apk app-release.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk
