name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew bundleDebug

    - name: Copy debug APK to root
      run: cp app/build/outputs/bundle/debug/app-debug.aab app-debug.aab

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: debug-bundle
        path: app/build/outputs/bundle/debug/app-debug.aab
