name: Android CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        api-level: [24, 34]
        gradle-version: [8.5]
        flavour: [freeVersion, paidVersion]
        module: [app, Playground]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          check-latest: true

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
            app/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ matrix.gradle-version }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run lint checks
        run: ./gradlew lint
        continue-on-error: true

      - name: Run unit tests
        run: ./gradlew test
        continue-on-error: true

      - name: Build with Gradle
        run: ./gradlew build
        continue-on-error: true

      - name: Build and sign release APK
        run: ./gradlew assembleRelease --stacktrace
        continue-on-error: true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk
        continue-on-error: true

      - name: Output details on failure
        if: failure()
        run: cat build/reports/*.html
        continue-on-error: true

      - name: Upload error logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: error-logs
          path: |
            build/*.log
            app/build/reports

      - name: Build and sign release APK for each variant
        # Use the gradle command with the flavour and module name as parameters
        run: ./gradlew ${{ matrix.module }}:assemble${{ matrix.flavour }}Release --stacktrace
        continue-on-error: true

      - name: Zip all the APK files
        # Zip all the APK files in the outputs folder
        run: zip -r apk.zip */build/outputs/apk/*/*.apk
        continue-on-error: true

      - name: Upload Zip APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          # Upload the zip file as an artifact
          path: apk.zip
        continue-on-error: true
